### ISSUE TITLE
[Bug]: Search input includes `location` to search for 

### ISSUE THREAD

**Issue by ParthJadhav** [ParthJadhav/rust_search#20]
```rust
let search: Vec<String> = SearchBuilder::default()
        .location("/System/")
        .search_input("Syste")
        .depth(1)
        .ignore_case()
        .build()
        .collect();
```

This will return everything contained in `/System/` directory because the Regex will be matched with the path input i.e /**Syste**m/ and return everything. 

This could be solved by adding: `.split("/").last().unwrap()` to `path`

```rust
reg_exp.is_match(&path.split("/").last().unwrap())
```

@TheAwiteb , Is there a better way to do this? Or are there any implications using this approach ?

**Comment by TheAwiteb** [comment]
Yes, we can use [`Path::file_name`](https://doc.rust-lang.org/std/path/struct.Path.html#method.file_name). Assign it to me, i'll solve it

**Comment by ParthJadhav** [comment]
Okay @TheAwiteb , Thanks a lot
