### ISSUE TITLE
[Feature Request]: Add search filters (Date Created, Date Modified, File Size)

### ISSUE THREAD

**Issue by songlinshu** [ParthJadhav/rust_search#3]
Hi ,Support for increasing file size, establishment time and modification time.

**Comment by ParthJadhav** [comment]
Hey @songlinshu , Can you elaborate more on what you said? It's quite hard to understand.

**Comment by songlinshu** [comment]
![image](https://user-images.githubusercontent.com/45619496/198872435-aecbfbcb-76a2-4529-a601-3c295e44ca1f.png)

**Comment by songlinshu** [comment]
![image](https://user-images.githubusercontent.com/45619496/198872445-38e8c726-37be-45a6-bdbe-79a8283c3438.png)

**Comment by songlinshu** [comment]
![image](https://user-images.githubusercontent.com/45619496/198872493-bf1cfb05-f654-4c8a-9923-3956f6d4132c.png)

**Comment by ParthJadhav** [comment]
That's a nice feature we can add.
