### ISSUE TITLE
Add it to Rust Awesome

### ISSUE THREAD

**Issue by TheAwiteb** [ParthJadhav/rust_search#32]
Of course because it's awesome. https://github.com/rust-unofficial/awesome-rust

**Comment by TheAwiteb** [comment]
This will close if https://github.com/rust-unofficial/awesome-rust/pull/1437 have merge

**Comment by ParthJadhav** [comment]
Thanks @TheAwiteb

**Comment by TheAwiteb** [comment]
Done, its has added https://github.com/rust-unofficial/awesome-rust/pull/1437
