### ISSUE TITLE
[Feature Request]: Make `Search` struct easier 

### ISSUE THREAD

**Issue by TheAwiteb** [ParthJadhav/rust_search#6]
**Breaking changes**

I think add `search` instance function to `Search` struct will make it easier. This will make it easier to do something like this

```rust
use rust_search::Search;

fn main() {
    let mains = Search::default().input("main").search();
    let readmes = Search::default().input("readme")
    .ignore_case() // will ignore ascii case
    .extension("md")
    .search();
}
```

**Comment by TheAwiteb** [comment]
If you don't mind adding this, I'm ready to add it 🚀

**Comment by ParthJadhav** [comment]
Go ahead @TheAwiteb 🚀 I'm out for a while
